apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      # the initContainers section is used to define the init containers that run before the app container
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      # the command that is executed in the init container to initialize the service before the app container starts
      command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
      
