apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
  # select the node to run the pod on 
  nodeName: node01

