apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - name: nginx-container 
      image: nginx
      # set the node selector for the pod
  nodeSelector:
    # the key is the label name and the value is the label value
    # in this case, the pod will be scheduled on a node with the label "size=large"
    size: Large


